Config-Version: 1
Lang: en_US
Debug: false
Items:
    Name:
        'TestItem':
            SaveOnDeath: true
            Use: false
            Drop: false
            PutToContainers: false
            PickUpIfExists: false
            MaxStack: 1
    ID:
        'minecraft:barrier':
            SaveOnDeath: true
            Use: false
            Drop: false
            PutToContainers: false
            PickUpIfExists: false
            MaxStack: 1